# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73ddf747115a6af6eb6aa03b65e65dd51f948cdf30044b5828179efa90060eda082579b3bd36e173916170c4d58c1994b4d6c07d280e27df5bc22305fcfe3c1c

test:
  secret_key_base: 4d3a3a9c1a46cc562006a2748f7c161fadedc9c06ba2b7f727e318f1703e1a3abd8c09c8cf330a110498249631b8d92779941ad4aa4a9c252fe60ce6b5eed1a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
